{{- if .Values.dockerhub_docker_config_json }}
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub
  namespace: {{ .Release.Namespace | quote }}
data:
  .dockerconfigjson: {{ .Values.dockerhub_docker_config_json | quote }}
type: kubernetes.io/dockerconfigjson
{{- end }}
