{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if eq .Values.tempo.deploymentMode "scalingMonolithic" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "grafana-tempo.scaling-monolithic.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: scaling-monolithic
  {{- if or .Values.commonAnnotations .Values.scalingMonolithic.service.annotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.scalingMonolithic.service.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.scalingMonolithic.service.type }}
  {{- if .Values.scalingMonolithic.service.sessionAffinity }}
  sessionAffinity: {{ .Values.scalingMonolithic.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.scalingMonolithic.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.scalingMonolithic.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if and .Values.scalingMonolithic.service.clusterIP (eq .Values.scalingMonolithic.service.type "ClusterIP") }}
  clusterIP: {{ .Values.scalingMonolithic.service.clusterIP }}
  {{- end }}
  {{- if or (eq .Values.scalingMonolithic.service.type "LoadBalancer") (eq .Values.scalingMonolithic.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.scalingMonolithic.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.scalingMonolithic.service.type "LoadBalancer") (not (empty .Values.scalingMonolithic.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.scalingMonolithic.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.scalingMonolithic.service.type "LoadBalancer") (not (empty .Values.scalingMonolithic.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.scalingMonolithic.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.scalingMonolithic.service.ports.http }}
      targetPort: http
      protocol: TCP
      {{- if (and (or (eq .Values.scalingMonolithic.service.type "NodePort") (eq .Values.scalingMonolithic.service.type "LoadBalancer")) (not (empty .Values.scalingMonolithic.service.nodePorts.http))) }}
      nodePort: {{ .Values.scalingMonolithic.service.nodePorts.http }}
      {{- else if eq .Values.scalingMonolithic.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    - name: grpc
      port: {{ .Values.scalingMonolithic.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
      {{- if (and (or (eq .Values.scalingMonolithic.service.type "NodePort") (eq .Values.scalingMonolithic.service.type "LoadBalancer")) (not (empty .Values.scalingMonolithic.service.nodePorts.grpc))) }}
      nodePort: {{ .Values.scalingMonolithic.service.nodePorts.grpc }}
      {{- else if eq .Values.scalingMonolithic.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    ## From here we use non-configurable, standard ports
    {{- if .Values.tempo.traces.jaeger.thriftCompact }}
    - name: distributor-jaeger-thrift-compact
      port: 6831
      protocol: UDP
      targetPort: jaeger-compact
    {{- end }}
    {{- if .Values.tempo.traces.jaeger.thriftBinary }}
    - name: distributor-jaeger-thrift-binary
      port: 6832
      protocol: UDP
      targetPort: jaeger-binary
    {{- end }}
    {{- if .Values.tempo.traces.jaeger.thriftHttp }}
    - name: distributor-jaeger-thrift-http
      port: 14268
      protocol: TCP
      targetPort: jaeger-http
    {{- end }}
    {{- if .Values.tempo.traces.jaeger.grpc }}
    - name: distributor-jaeger-grpc
      port: 14250
      protocol: TCP
      targetPort: jaeger-grpc
    {{- end }}
    {{- if .Values.tempo.traces.zipkin }}
    - name: distributor-zipkin
      port: 9411
      protocol: TCP
      targetPort: zipkin
    {{- end }}
    {{- if .Values.tempo.traces.otlp.http }}
    - name: distributor-otlp-http
      port: 4318
      protocol: TCP
      targetPort: otlp-http
    - name: distributor-otlp-http-legacy
      port: 55681
      protocol: TCP
      targetPort: otlp-http
    {{- end }}
    {{- if .Values.tempo.traces.otlp.grpc }}
    - name: distributor-otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: otlp-grpc
    - name: distributor-otlp-grpc-legacy
      port: 55680
      protocol: TCP
      targetPort: otlp-grpc
    {{- end }}
    {{- if .Values.tempo.traces.opencensus }}
    - name: distributor-opencensus
      port: 55678
      protocol: TCP
      targetPort: opencensus
    {{- end }}
    {{- if .Values.scalingMonolithic.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.scalingMonolithic.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.scalingMonolithic.podLabels .Values.commonLabels ) "context" . ) }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: scaling-monolithic
{{- end }}
