---
{{- $oldSecret := lookup "v1" "Secret" .Release.Namespace .Values.global.mist.org.secretName }}
{{- $password := "" }}
{{- if or (not $oldSecret) (not $oldSecret.data) }}
  {{- $password = uuidv4 | replace "-" "" | b64enc }}
{{- else }}
  {{- $password = index $oldSecret.data "org-id" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.mist.org.secretName }}
  labels:
    app: hzp
type: Opaque
data:
  org-id: {{ $password | quote }}
  org-name: {{ "Dell" | b64enc | quote }}
